# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/ReactiveDataSource.xcworkspace -scheme ReactiveDataSource -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
